### ISSUE TITLE
namespace is wrong

### ISSUE THREAD

**Issue by guyvanbael** [vinstah/silverstripe-designer#12]
Doesn't install... namespace in config.yml should be...
Silverstripe\CMS\Model\SiteTree:
  extensions:
    - NzVvveb\SilverstripeDesigner\Extension\DesignerExtension

**Comment by vinstah** [comment]
Hi,

Sorry for the late reply, 
thanks for letting me know.

**Comment by vinstah** [comment]
fixed #13
